### ISSUE TITLE
Javascript is breaking in firefox without reporting error.

### ISSUE THREAD

**Issue by jmtcsngr** [wtsi-npg/npg_qc#194]
Users report application randomly stops generating controls for MQC when using firefox. No error is reported. The page generates properly after reloading.

**Comment by jmtcsngr** [comment]
![failure to load all page data](https://cloud.githubusercontent.com/assets/10711639/8720392/6119af46-2baa-11e5-83d4-0f7cf83df1e6.png)

**Comment by jmtcsngr** [comment]
![failure to load all page data](https://cloud.githubusercontent.com/assets/10711639/8720422/93d0ead0-2baa-11e5-8554-6534ecdf097e.png)

**Comment by mgcam** [comment]
No reports since July
