### ISSUE TITLE
Unable to properly deflate for historic tables.

### ISSUE THREAD

**Issue by jmtcsngr** [wtsi-npg/npg_qc#253]
Historic tables for lane and plex level library qc have problems when deflating. Both historic tables were designed without a unique key for id_run/position and id_run/position/tag_index. They only work with a numeric primary key to identify each row. Because deflate works with the table definition (unique key), it can not properly deflate null value in tag_index. This can cause problems if using deflate before a search. As the null value will no be changed to the default value (-1) so it will not find the rows specified in the condition.

**Comment by mgcam** [comment]
This is  a low priority issue since search on _hist tables is not performed in production.

**Comment by jmtcsngr** [comment]
Now mqc tables are composition based.
