### ISSUE TITLE
upstream_tags check should decode with bambi

### ISSUE THREAD

**Issue by dozy** [wtsi-npg/npg_qc#402]
the upstream_tags check (npg_qc/autoqc/checks/upstream_tags.pm) should use bambi instead of BamIndexDecoder for its decoding (see BamIndexDecoder_cmd attribute)

**Comment by mgcam** [comment]
resolved via https://github.com/wtsi-npg/npg_qc/commit/3c7d4e312a83856e002bb52f00af76e2c1d454e4#diff-cbc1a66ee94b68aac1119acb619eaf4c
