### ISSUE TITLE
qc_db_delete_autoqc doesn't work for QC checks which use id_seq_composition

### ISSUE THREAD

**Issue by srl147** [wtsi-npg/npg_qc#423]
there are two problems with qc_db_delete_autoqc

firstly checks_list function has moved from npg_qc::autoqc::autoqc to npg_qc::autoqc::results::collection

secondly the code assume all the database table have a id_run column, this isn't true for qc checks which use composition i.e.

rna_seqqc, samtools_stats and sequence_summary

**Comment by mgcam** [comment]
Resolved in https://github.com/wtsi-npg/npg_qc/pull/424
