### ISSUE TITLE
Remove redundant PATH setting from Action config

### ISSUE THREAD

**Issue by kjsanger** [wtsi-npg/npg_qc#754]
https://github.com/wtsi-npg/npg_qc/blob/62f6394cfc560b881564dd4063a084042180fc53/.github/workflows/testing_and_building_repos.yml#L75

This path doesn't need to be set - it's handled by Conda activation and will break if Conda is moved

**Comment by mgcam** [comment]
This line is no longer present in the current HED (e7e5c616bc5df97d9c412ad832d2f4560daa4937) of wtsi/devel
