### ISSUE TITLE
Remove redundant PATH setting from Action config

### ISSUE THREAD

**Issue by kjsanger** [wtsi-npg/npg_qc#755]
https://github.com/wtsi-npg/npg_qc/blob/62f6394cfc560b881564dd4063a084042180fc53/.github/workflows/testing_and_building_repos.yml#L89

This path doesn't need to be set - it's handled by Conda activation and will break if Conda is moved

**Comment by mgcam** [comment]
Resolved by https://github.com/wtsi-npg/npg_qc/pull/760
