### ISSUE TITLE
Request for assistance identifying PDL problem

### ISSUE THREAD

**Issue by mohawk2** [wtsi-npg/npg_qc#798]
A comment on https://github.com/wtsi-npg/npg_qc/pull/792 caused a notification on https://github.com/PDLPorters/pdl/issues/369. It refers to a problem in your `reverse_average_percent_error` with recent versions of PDL. I thought it better to ask rather than go through the agony of installing all your internal prereqs to be sure.

It appears to me that this bit of code:

```perl
sub reverse_average_percent_error {
[...]
  my $error_rate_by_cycle = pdl($self->reverse_errors||[])/ pdl( $total_count );
```

might be causing an error if it passes an empty PDL along. But in any case, if you could show either here or on an issue on the PDL repo the bit of code and relevant data that is not behaving as you expect, then we can capture that in a test and fix it!

**Comment by mohawk2** [comment]
To add to the above: in the last few weeks, PDL has added downstream testing of all known working CPAN downstream (about 60 projects) on every commit, which has already caught a couple of errors. We'd love to be able to support real scientists by adding your work against that, though it might take a little bit of effort to install your prereqs.

**Comment by nerdstrike** [comment]
@mohawk2 - thanks for taking an interest!

We started seeing failures in our github CI e.g. https://github.com/wtsi-npg/npg_qc/runs/5231738856?check_suite_focus=true . If I run the specific test on an Ubuntu 18.04 VM with PDL 2.077 or 2.069, I also see:
```
Segmentation fault (core dumped)
```
You are right to point to `reverse_average_percent_error`.

When I strip away the complexity and get to the test data, it seems the error arises as follows:
```
my $a = pdl(undef||[]);
my $b = pdl(undef);
my $error_rate_by_cycle = $a/$b;
my $stats = stats($error_rate_by_cycle);
```
and...
```
print PDL->px($error_rate_by_cycle);
----
Empty[0]
```

I realise it's silly to compute stats on undef, but our input data is very variable and we've been getting away with it up to versions 2.069. I'm not sure a seqfault would be considered a graceful way to handle it!

**Comment by mohawk2** [comment]
For future reference, we really want to know about problems like this - the idea that library users would want to version-pin (except as a temporary emergency measure) and not feel like reporting the problem is very troubling! Obviously, any segfault problem is considered a disaster.

Also, thank you for taking the time to check this error against the latest-released PDL.

I've reduced this down to a laughably small test-case, which segfaults:

`stats(empty())`

**Comment by mohawk2** [comment]
@nerdstrike The above-linked commit fixes this by throwing an exception if `medover` (and by extension, `stats` which calls it) et al are called on an empty ndarray. My rationale is that this was never valid, and an exception is the only legitimate action.

Before I release that with a new PDL 2.078 (which is due in any case), could you please install the git-latest PDL and check there aren't any other uses of empty ndarrays in your codebase that might also blow up? This is all due to a change in memory-handling where empty ndarrays now don't get memory allocated, where before they did so this sort of thing worked by coincidence.

Naturally, if you have objections and/or a better approach for this, please say on here :-)

**Comment by nerdstrike** [comment]
@mohawk2 - Building PDL from master I now get the exception: `Error in medover:cannot process empty ndarray`

I'll log some future work to clear out our misuse of PDL, as at least we can now see what needs to change. Thank you for explaining what has changed.
